### ISSUE TITLE
针对CMeEE数据集，没有POS词性标注，我应该用什么方法对CMeEE数据集做词性标注使其能满足在这个模型上训练？

### ISSUE THREAD

**Issue by antheaxiang** [Rosenberg37/GraphNER#3]

**Comment by wenxueru** [comment]
使用其他的工具对数据集做POS标注，或者不使用POS标注（它不是必须的，只是可选的）

**Comment by antheaxiang** [comment]
我的数据集是中文嵌套数据集CMeEE，看了您WeiboNER的POS标注，发现LTP分词和jieba分词都不能满足
这样的标注，我应该用什么分词工具满足这样的标注呢？您那边还有修改中文嵌套数据集的脚本吗？其次，我还想在您的模型上做一点创新，您有好的点子可以分享一下吗？

**Comment by wenxueru** [comment]
> 我的数据集是中文嵌套数据集CMeEE，看了您WeiboNER的POS标注，发现LTP分词和jieba分词都不能满足 这样的标注，我应该用什么分词工具满足这样的标注呢？您那边还有修改中文嵌套数据集的脚本吗？其次，我还想在您的模型上做一点创新，您有好的点子可以分享一下吗？

你可以尝试用其他一些模型标。其次这个工作是前LLMs的，我觉得在LLMs的时代Nested NER已经不是个问题了。
