### ISSUE TITLE
关于RuntimeError： Sizes of tensors must match except in dimension 1.

### ISSUE THREAD

**Issue by ZCappuccino** [Rosenberg37/GraphNER#4]
您好！我更换了自己的数据集在您的代码上运行，其中因为该数据没有POS词性标记，所以我这里的数据设置了空列表，并将数据修改成了模型支持的格式，但是运行时出现了这样的问题：
Traceback (most recent call last):
  File "/root/pyprojects/GraphNER/main.py", line 28, in <module>
    trainer()
  File "/root/pyprojects/GraphNER/utils/train.py", line 64, in __call__
    loss = self.model(data)
  File "/root/anaconda3/envs/GraphNER/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/pyprojects/GraphNER/modules/model/NER.py", line 76, in forward
    context, types, mask = self.encoder(batch_sentences)
  File "/root/anaconda3/envs/GraphNER/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/pyprojects/GraphNER/modules/model/encode.py", line 50, in forward
    batch_embeds, mask = self.embedding(batch_sentences)
  File "/root/anaconda3/envs/GraphNER/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/pyprojects/GraphNER/modules/model/encode.py", line 108, in forward
    batch_embeds = torch.cat(embeds, dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 0 and 40 (The offending index is 0)
请问这样的问题应该怎样解决呢？

**Comment by wenxueru** [comment]
印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。

**Comment by CharlesStarla** [comment]
> 印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。

谢谢您！我把数据中的pos去掉，同时metadata.json中的pos也去掉了，在运行时，没有设置pos_dim=50，但是出现了这样的错误：
Traceback (most recent call last):
  File "/root/pyprojects/GraphNER/main.py", line 16, in <module>
    corpus = modules.FormatCorpus(**vars(config.DATA_OPTIONS))
  File "/root/pyprojects/GraphNER/modules/data.py", line 209, in __init__
    self._train: FormatDataset = self.create_dataset(dataset_path, 'train', mini_size)
  File "/root/pyprojects/GraphNER/modules/data.py", line 235, in create_dataset
    dataset = FormatDataset(file, mode, mini_size)
  File "/root/pyprojects/GraphNER/modules/data.py", line 123, in __init__
    self._sentences = self.format(data_list)
  File "/root/pyprojects/GraphNER/modules/data.py", line 133, in format
    sentence.add_label('pos', data['pos'])
KeyError: 'pos'
请问是不是data.py中有关pos的设置全部都要去掉呢？encode.py中需要修改吗？

**Comment by ZCappuccino** [comment]
> 印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。

谢谢您！我把数据中的pos去掉，同时metadata.json中的pos也去掉了，在运行时，没有设置pos_dim=50，但是出现了这样的错误：
Traceback (most recent call last):
  File "/root/pyprojects/GraphNER/main.py", line 16, in <module>
    corpus = modules.FormatCorpus(**vars(config.DATA_OPTIONS))
  File "/root/pyprojects/GraphNER/modules/data.py", line 209, in __init__
    self._train: FormatDataset = self.create_dataset(dataset_path, 'train', mini_size)
  File "/root/pyprojects/GraphNER/modules/data.py", line 235, in create_dataset
    dataset = FormatDataset(file, mode, mini_size)
  File "/root/pyprojects/GraphNER/modules/data.py", line 123, in __init__
    self._sentences = self.format(data_list)
  File "/root/pyprojects/GraphNER/modules/data.py", line 133, in format
    sentence.add_label('pos', data['pos'])
KeyError: 'pos'

请问是不是data.py中有关pos的设置全部都要去掉呢？encode.py中需要修改吗？

**Comment by wenxueru** [comment]
> > 印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。
> 
> 谢谢您！我把数据中的pos去掉，同时metadata.json中的pos也去掉了，在运行时，没有设置pos_dim=50，但是出现了这样的错误： Traceback (most recent call last): File "/root/pyprojects/GraphNER/main.py", line 16, in corpus = modules.FormatCorpus(**vars(config.DATA_OPTIONS)) File "/root/pyprojects/GraphNER/modules/data.py", line 209, in **init** self._train: FormatDataset = self.create_dataset(dataset_path, 'train', mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 235, in create_dataset dataset = FormatDataset(file, mode, mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 123, in **init** self._sentences = self.format(data_list) File "/root/pyprojects/GraphNER/modules/data.py", line 133, in format sentence.add_label('pos', data['pos']) KeyError: 'pos'
> 
> 请问是不是data.py中有关pos的设置全部都要去掉呢？encode.py中需要修改吗？

可能data.py里相关的注释了就好

**Comment by ZCappuccino** [comment]
> > > 印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。
> > 
> > 
> > 谢谢您！我把数据中的pos去掉，同时metadata.json中的pos也去掉了，在运行时，没有设置pos_dim=50，但是出现了这样的错误： Traceback (most recent call last): File "/root/pyprojects/GraphNER/main.py", line 16, in corpus = modules.FormatCorpus(**vars(config.DATA_OPTIONS)) File "/root/pyprojects/GraphNER/modules/data.py", line 209, in **init** self._train: FormatDataset = self.create_dataset(dataset_path, 'train', mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 235, in create_dataset dataset = FormatDataset(file, mode, mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 123, in **init** self._sentences = self.format(data_list) File "/root/pyprojects/GraphNER/modules/data.py", line 133, in format sentence.add_label('pos', data['pos']) KeyError: 'pos'
> > 请问是不是data.py中有关pos的设置全部都要去掉呢？encode.py中需要修改吗？
> 
> 可能data.py里相关的注释了就好

谢谢您！还有一个问题想问问您，我在运行中出现了TypeError: cannot unpack non-iterable NoneType object的问题，报错语句是s, e = encoding.word_to_tokens(i, j)，我看了encode.py，并没有体现word_to_tokens()这个函数，想问问您它是如何实现的？

**Comment by wenxueru** [comment]
> > > > 印象里没有POS标记的话直接数据没有这个键，参数里相关的别设置就行，不用设置为空列表。
> > > 
> > > 
> > > 谢谢您！我把数据中的pos去掉，同时metadata.json中的pos也去掉了，在运行时，没有设置pos_dim=50，但是出现了这样的错误： Traceback (most recent call last): File "/root/pyprojects/GraphNER/main.py", line 16, in corpus = modules.FormatCorpus(**vars(config.DATA_OPTIONS)) File "/root/pyprojects/GraphNER/modules/data.py", line 209, in **init** self._train: FormatDataset = self.create_dataset(dataset_path, 'train', mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 235, in create_dataset dataset = FormatDataset(file, mode, mini_size) File "/root/pyprojects/GraphNER/modules/data.py", line 123, in **init** self._sentences = self.format(data_list) File "/root/pyprojects/GraphNER/modules/data.py", line 133, in format sentence.add_label('pos', data['pos']) KeyError: 'pos'
> > > 请问是不是data.py中有关pos的设置全部都要去掉呢？encode.py中需要修改吗？
> > 
> > 
> > 可能data.py里相关的注释了就好
> 
> 谢谢您！还有一个问题想问问您，我在运行中出现了TypeError: cannot unpack non-iterable NoneType object的问题，报错语句是s, e = encoding.word_to_tokens(i, j)，我看了encode.py，并没有体现word_to_tokens()这个函数，想问问您它是如何实现的？

这应该在我实现时那个版本的hugginface transformers库提供的方法，最新版本应该同样有类似的函数，你可以ref doc
